export type MasterpieceActivationReadiness = "Ready" | "Review" | "Hold";

export type MasterpieceActivationRow = {
  rank: number;
  ncId: string;
  title: string;
  illustrator: string;
  year: string;
  institution: string;
  collection: string;
  rights: string;
  commerce: string;
  revenueTier: "MASTERWORK" | "FLAGSHIP" | "STANDARD" | "REVIEW";
  score: number;
  wave: "Wave 1" | "Wave 2" | "Wave 3";
  readiness: MasterpieceActivationReadiness;
  blockingAction: string;
};

export const masterpieceActivationSummary = {
  document: "NC-MASTERPIECES-002",
  top25Count: 25,
  immediateLaunchCount: 9,
  wave1Count: 17,
  wave2Count: 6,
  wave3BlockedCount: 2
};

export const masterpieceActivationRows: MasterpieceActivationRow[] = [
  {
    rank: 1,
    ncId: "NC-NHM-NH-00001",
    title: "Thylacine (Tasmanian Tiger)",
    illustrator: "Gould",
    year: "c. 1845",
    institution: "Natural History Museum",
    collection: "Extinction Archive",
    rights: "NHM CC0, DD-NHM-001 pending",
    commerce: "Museum Giclee, CE eligible",
    revenueTier: "MASTERWORK",
    score: 59,
    wave: "Wave 2",
    readiness: "Review",
    blockingAction: "Ratify DD-NHM-001"
  },
  {
    rank: 2,
    ncId: "NC-BHL-NH-00001",
    title: "Carolina Parakeet",
    illustrator: "Audubon",
    year: "1827",
    institution: "BHL / Smithsonian",
    collection: "Extinction Archive",
    rights: "BHL pre-1928 PD, Smithsonian upgrade pending",
    commerce: "Paired portfolio, Family A pending resolution",
    revenueTier: "MASTERWORK",
    score: 58,
    wave: "Wave 1",
    readiness: "Review",
    blockingAction: "Confirm BHL T1 image >= 6000 px"
  },
  {
    rank: 3,
    ncId: "NC-BHL-NH-00002",
    title: "Passenger Pigeon",
    illustrator: "Audubon",
    year: "1827",
    institution: "BHL / Smithsonian",
    collection: "Extinction Archive",
    rights: "BHL pre-1928 PD, Smithsonian upgrade pending",
    commerce: "Paired portfolio, Family A pending resolution",
    revenueTier: "MASTERWORK",
    score: 58,
    wave: "Wave 1",
    readiness: "Review",
    blockingAction: "Confirm BHL T1 image >= 6000 px"
  },
  {
    rank: 4,
    ncId: "NC-BHL-NH-00003",
    title: "Radiolaria",
    illustrator: "Haeckel",
    year: "1904",
    institution: "Biodiversity Heritage Library",
    collection: "Natural History Masterwork",
    rights: "BHL T1 public domain",
    commerce: "Museum Giclee + Digital",
    revenueTier: "MASTERWORK",
    score: 58,
    wave: "Wave 1",
    readiness: "Ready",
    blockingAction: "None"
  },
  {
    rank: 5,
    ncId: "NC-BHL-NH-00004",
    title: "Darwin's Finches",
    illustrator: "Gould / Darwin",
    year: "1839",
    institution: "Biodiversity Heritage Library",
    collection: "Expedition Record",
    rights: "BHL public domain",
    commerce: "NC-PROD-005 active",
    revenueTier: "FLAGSHIP",
    score: 58,
    wave: "Wave 1",
    readiness: "Review",
    blockingAction: "SA ratification for Galapagos place page"
  },
  {
    rank: 6,
    ncId: "NC-NHM-NH-00003",
    title: "Platypus",
    illustrator: "Nodder",
    year: "1799",
    institution: "Natural History Museum",
    collection: "Expedition Record",
    rights: "NHM CC0, DD-NHM-001 pending",
    commerce: "Museum Giclee",
    revenueTier: "FLAGSHIP",
    score: 58,
    wave: "Wave 2",
    readiness: "Review",
    blockingAction: "Ratify DD-NHM-001"
  },
  {
    rank: 7,
    ncId: "NC-BHL-NH-00009",
    title: "Marvelous Spatuletail",
    illustrator: "Gould",
    year: "1849-61",
    institution: "BHL / Natural History Museum",
    collection: "Natural History Masterwork",
    rights: "BHL / NHM T1",
    commerce: "Museum Giclee",
    revenueTier: "FLAGSHIP",
    score: 58,
    wave: "Wave 1",
    readiness: "Review",
    blockingAction: "Confirm BHL T1 image >= 6000 px"
  },
  {
    rank: 8,
    ncId: "NC-BHL-NH-00005",
    title: "Wild Turkey",
    illustrator: "Audubon",
    year: "1827",
    institution: "BHL / Smithsonian",
    collection: "Natural History Masterwork",
    rights: "BHL pre-1928 PD, Smithsonian upgrade pending",
    commerce: "Museum Giclee",
    revenueTier: "FLAGSHIP",
    score: 57,
    wave: "Wave 1",
    readiness: "Review",
    blockingAction: "Confirm BHL T1 image >= 6000 px"
  },
  {
    rank: 9,
    ncId: "NC-BHL-NH-00006",
    title: "Bald Eagle",
    illustrator: "Audubon",
    year: "1827",
    institution: "Biodiversity Heritage Library",
    collection: "Natural History Masterwork",
    rights: "BHL public domain",
    commerce: "Museum Giclee",
    revenueTier: "FLAGSHIP",
    score: 57,
    wave: "Wave 1",
    readiness: "Ready",
    blockingAction: "None"
  },
  {
    rank: 10,
    ncId: "NC-BHL-NH-00007",
    title: "American Bison",
    illustrator: "Audubon",
    year: "1846",
    institution: "Biodiversity Heritage Library",
    collection: "Natural History Masterwork",
    rights: "BHL public domain",
    commerce: "Yellowstone anchor asset",
    revenueTier: "FLAGSHIP",
    score: 57,
    wave: "Wave 1",
    readiness: "Review",
    blockingAction: "NC-DATA-001 Yellowstone place page live"
  },
  {
    rank: 11,
    ncId: "NC-BHL-NH-00008",
    title: "Pomegranate with Caterpillar",
    illustrator: "Merian",
    year: "1705",
    institution: "Biodiversity Heritage Library",
    collection: "Botanical Canon",
    rights: "BHL T1 public domain",
    commerce: "Museum Giclee + Education Pack",
    revenueTier: "FLAGSHIP",
    score: 57,
    wave: "Wave 1",
    readiness: "Ready",
    blockingAction: "None"
  },
  {
    rank: 12,
    ncId: "NC-NHM-NH-00004",
    title: "Kangaroo",
    illustrator: "Parkinson",
    year: "1770",
    institution: "Natural History Museum",
    collection: "Expedition Record",
    rights: "NHM CC0, DD-NHM-001 pending",
    commerce: "Australia Collection pair",
    revenueTier: "FLAGSHIP",
    score: 57,
    wave: "Wave 2",
    readiness: "Review",
    blockingAction: "Ratify DD-NHM-001"
  },
  {
    rank: 13,
    ncId: "NC-NHM-NH-00002",
    title: "Strelitzia reginae",
    illustrator: "Parkinson / Banks",
    year: "1771",
    institution: "Natural History Museum",
    collection: "Expedition Record",
    rights: "NHM CC0, DD-NHM-001 pending",
    commerce: "Australia Collection pair",
    revenueTier: "FLAGSHIP",
    score: 57,
    wave: "Wave 2",
    readiness: "Review",
    blockingAction: "Ratify DD-NHM-001"
  },
  {
    rank: 14,
    ncId: "NC-BHL-NH-00011",
    title: "Whooping Crane",
    illustrator: "Audubon",
    year: "1834",
    institution: "Biodiversity Heritage Library",
    collection: "Natural History Masterwork",
    rights: "BHL public domain",
    commerce: "Museum Giclee",
    revenueTier: "FLAGSHIP",
    score: 57,
    wave: "Wave 1",
    readiness: "Review",
    blockingAction: "Assign GeoNames ID for Aransas NWR"
  },
  {
    rank: 15,
    ncId: "NC-BHL-NH-00012",
    title: "Ivory-billed Woodpecker",
    illustrator: "Catesby",
    year: "1731",
    institution: "Biodiversity Heritage Library",
    collection: "Extinction Archive",
    rights: "BHL pre-1928 PD, tier verification pending",
    commerce: "Museum Giclee",
    revenueTier: "FLAGSHIP",
    score: 57,
    wave: "Wave 1",
    readiness: "Review",
    blockingAction: "Confirm BHL tier for Catesby 1731"
  },
  {
    rank: 16,
    ncId: "NC-BHL-SCI-00001",
    title: "Tableau physique des Andes",
    illustrator: "Humboldt / Bonpland",
    year: "1807",
    institution: "BHL / MNHN",
    collection: "Scientific Diagram",
    rights: "MNHN access and ToS unconfirmed",
    commerce: "Curriculum licence + archival print",
    revenueTier: "REVIEW",
    score: 57,
    wave: "Wave 3",
    readiness: "Hold",
    blockingAction: "Draft DD-MNHN-001"
  },
  {
    rank: 17,
    ncId: "NC-SPRI-NH-00001",
    title: "Emperor Penguin with Chick",
    illustrator: "Wilson",
    year: "1902-04",
    institution: "Scott Polar Research Institute",
    collection: "Expedition Record",
    rights: "SPRI ToS unconfirmed",
    commerce: "Museum Giclee, South Georgia anchor",
    revenueTier: "REVIEW",
    score: 56,
    wave: "Wave 3",
    readiness: "Hold",
    blockingAction: "Draft DD-SPRI-001"
  },
  {
    rank: 18,
    ncId: "NC-MET-CL-00001",
    title: "Under the Great Wave off Kanagawa",
    illustrator: "Hokusai",
    year: "c. 1831",
    institution: "Metropolitan Museum of Art",
    collection: "Cultural Anchor",
    rights: "Met CC0, DD-MET-001 pending",
    commerce: "Museum Giclee + Japan Collection anchor",
    revenueTier: "MASTERWORK",
    score: 56,
    wave: "Wave 2",
    readiness: "Review",
    blockingAction: "Ratify DD-MET-001"
  },
  {
    rank: 19,
    ncId: "NC-BHL-NH-00015",
    title: "Hyacinth Macaw",
    illustrator: "Lear",
    year: "1832",
    institution: "BHL / Natural History Museum",
    collection: "Natural History Masterwork",
    rights: "BHL / NHM T1 public domain",
    commerce: "Museum Giclee",
    revenueTier: "FLAGSHIP",
    score: 55,
    wave: "Wave 1",
    readiness: "Ready",
    blockingAction: "None"
  },
  {
    rank: 20,
    ncId: "NC-BHL-NH-00013",
    title: "Medusae",
    illustrator: "Haeckel",
    year: "1904",
    institution: "Biodiversity Heritage Library",
    collection: "Natural History Masterwork",
    rights: "BHL T1 public domain",
    commerce: "Museum Giclee + Digital",
    revenueTier: "FLAGSHIP",
    score: 55,
    wave: "Wave 1",
    readiness: "Ready",
    blockingAction: "None"
  },
  {
    rank: 21,
    ncId: "NC-BHL-NH-00022",
    title: "Blue Morpho metamorphosis sequence",
    illustrator: "Merian",
    year: "1705",
    institution: "Biodiversity Heritage Library",
    collection: "Natural History Masterwork",
    rights: "BHL T1 public domain",
    commerce: "Museum Giclee + Education Pack",
    revenueTier: "FLAGSHIP",
    score: 55,
    wave: "Wave 1",
    readiness: "Ready",
    blockingAction: "None"
  },
  {
    rank: 22,
    ncId: "NC-WALTERS-CL-00001",
    title: "The Treasury (Khazneh), Petra",
    illustrator: "David Roberts",
    year: "1839",
    institution: "Walters Art Museum",
    collection: "Cultural Anchor",
    rights: "Walters CC0, DD-WALTERS-001 pending",
    commerce: "Museum Giclee + Petra Collection anchor",
    revenueTier: "MASTERWORK",
    score: 54,
    wave: "Wave 2",
    readiness: "Review",
    blockingAction: "Ratify DD-WALTERS-001"
  },
  {
    rank: 23,
    ncId: "NC-BHL-NH-00024",
    title: "Siphonophorae",
    illustrator: "Haeckel",
    year: "1904",
    institution: "Biodiversity Heritage Library",
    collection: "Scientific Diagram",
    rights: "BHL T1 public domain",
    commerce: "Museum Giclee",
    revenueTier: "STANDARD",
    score: 54,
    wave: "Wave 1",
    readiness: "Ready",
    blockingAction: "None"
  },
  {
    rank: 24,
    ncId: "NC-BHL-NH-00016",
    title: "Ammonites",
    illustrator: "Haeckel",
    year: "1904",
    institution: "Biodiversity Heritage Library",
    collection: "Natural History Masterwork",
    rights: "BHL T1 public domain",
    commerce: "Museum Giclee + Education",
    revenueTier: "STANDARD",
    score: 53,
    wave: "Wave 1",
    readiness: "Ready",
    blockingAction: "None"
  },
  {
    rank: 25,
    ncId: "NC-BHL-NH-00014",
    title: "Discomedusae",
    illustrator: "Haeckel",
    year: "1904",
    institution: "Biodiversity Heritage Library",
    collection: "Natural History Masterwork",
    rights: "BHL T1 public domain",
    commerce: "Museum Giclee",
    revenueTier: "STANDARD",
    score: 53,
    wave: "Wave 1",
    readiness: "Ready",
    blockingAction: "None"
  }
];

export const masterpieceActivationReadinessCounts = masterpieceActivationRows.reduce<
  Record<MasterpieceActivationReadiness, number>
>(
  (counts, row) => {
    counts[row.readiness] += 1;
    return counts;
  },
  { Ready: 0, Review: 0, Hold: 0 }
);
