"""Deterministic local mock provider."""

from __future__ import annotations

from typing import Any

from services.ai.prompts import stable_hash


class DeterministicMockProvider:
    provider = "local"
    model_name = "deterministic-mock-v1"
    external_calls_allowed = False

    def generate(self, prompt: str, context: dict[str, Any]) -> dict[str, Any]:
        digest = stable_hash({"prompt": prompt, "context": context})
        task_type = context.get("task_type")
        inputs = context.get("inputs") or {}
        product = inputs.get("product") or {}
        nasa_record = inputs.get("nasa_source_record") or {}
        title = product.get("title") or nasa_record.get("title") or "Earthrise"
        source_record_id = nasa_record.get("source_record_id") or "AS08-14-2383"
        rights_basis = nasa_record.get("rights_basis") or "17 U.S.C. § 105"

        if task_type == "product_copy":
            text = (
                f"{title} is a manually fulfilled Nature & Culture product grounded in NASA "
                f"source record {source_record_id}. The work is treated as public domain under "
                f"{rights_basis}; source credit and nonendorsement must remain visible wherever "
                "the product copy appears."
            )
        elif task_type == "place_story":
            text = (
                f"Story variant: Earthrise, photographed during Apollo 8, is presented here "
                f"through NASA source record {source_record_id}. The draft may discuss the image's "
                "historical and cultural importance, but it remains advisory copy pending human "
                "review and cannot imply agency endorsement."
            )
        elif task_type == "education_module":
            text = (
                f"Educational summary: Earthrise is a NASA Apollo 8 photograph associated with "
                f"source record {source_record_id}. Learners should understand the image, its "
                f"public-domain basis under {rights_basis}, and the requirement to preserve NASA "
                "credit and nonendorsement."
            )
        else:
            text = (
                "Draft advisory content generated by deterministic local mock. "
                "Human review is required before publication."
            )

        return {
            "text": text,
            "model_output_sha256": digest,
            "source_references": context.get("source_references", []),
            "publication_allowed": False,
        }
